export const CREATE_REAL_ESTATE_REQUEST = "CREATE_REAL_ESTATE_REQUEST";
export const CREATE_REAL_ESTATE_SUCCESS = "CREATE_REAL_ESTATE_SUCCESS";
export const CREATE_REAL_ESTATE_FAILURE = "CREATE_REAL_ESTATE_FAILURE";

export const GET_ALL_REAL_ESTATES_REQUEST = "GET_ALL_REAL_ESTATES_REQUEST";
export const GET_ALL_REAL_ESTATES_SUCCESS = "GET_ALL_REAL_ESTATES_SUCCESS";
export const GET_ALL_REAL_ESTATES_FAILURE = "GET_ALL_REAL_ESTATES_FAILURE";

export const DELETE_REAL_ESTATE_REQUEST = "DELETE_REAL_ESTATE_REQUEST";
export const DELETE_REAL_ESTATE_SUCCESS = "DELETE_REAL_ESTATE_SUCCESS";
export const DELETE_REAL_ESTATE_FAILURE = "DELETE_REAL_ESTATE_FAILURE";

export const UPDATE_REAL_ESTATE_REQUEST = "UPDATE_REAL_ESTATE_REQUEST";
export const UPDATE_REAL_ESTATE_SUCCESS = "UPDATE_REAL_ESTATE_SUCCESS";
export const UPDATE_REAL_ESTATE_FAILURE = "UPDATE_REAL_ESTATE_FAILURE";

export const GET_REAL_ESTATE_BY_ID_REQUEST = "GET_REAL_ESTATE_BY_ID_REQUEST";
export const GET_REAL_ESTATE_BY_ID_SUCCESS = "GET_REAL_ESTATE_BY_ID_SUCCESS";
export const GET_REAL_ESTATE_BY_ID_FAILURE = "GET_REAL_ESTATE_BY_ID_FAILURE";

export const GET_REAL_ESTATE_BY_USER_ID_REQUEST =
  "GET_REAL_ESTATE_BY_USER_ID_REQUEST";
export const GET_REAL_ESTATE_BY_USER_ID_SUCCESS =
  "GET_REAL_ESTATE_BY_USER_ID_SUCCESS";
export const GET_REAL_ESTATE_BY_USER_ID_FAILURE =
  "GET_REAL_ESTATE_BY_USER_ID_FAILURE";

export const UPDATE_REAL_ESTATE_STATUS_REQUEST =
  "UPDATE_REAL_ESTATE_STATUS_REQUEST";
export const UPDATE_REAL_ESTATE_STATUS_SUCCESS =
  "UPDATE_REAL_ESTATE_STATUS_SUCCESS";
export const UPDATE_REAL_ESTATE_STATUS_FAILURE =
  "UPDATE_REAL_ESTATE_STATUS_FAILURE";

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

export const GET_REAL_ESTATE_EVENTS_REQUEST = "GET_REAL_ESTATE_EVENTS_REQUEST";
export const GET_REAL_ESTATE_EVENTS_SUCCESS = "GET_REAL_ESTATE_EVENTS_SUCCESS";
export const GET_REAL_ESTATE_EVENTS_FAILURE = "GET_REAL_ESTATE_EVENTS_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_REAL_ESTATE_CATEGORY_REQUEST =
  "GET_REAL_ESTATE_CATEGORY_REQUEST";
export const GET_REAL_ESTATE_CATEGORY_SUCCESS =
  "GET_REAL_ESTATE_CATEGORY_SUCCESS";
export const GET_REAL_ESTATE_CATEGORY_FAILURE =
  "GET_REAL_ESTATE_CATEGORY_FAILURE";
