export const CREATE_KEY_REQUEST = "CREATE_KEY_REQUEST";
export const CREATE_KEY_SUCCESS = "CREATE_KEY_SUCCESS";
export const CREATE_KEY_FAILURE = "CREATE_KEY_FAILURE";

export const GET_USERS_KEYS_REQUEST = "GET_USERS_KEYS_REQUEST";
export const GET_USERS_KEYS_SUCCESS = "GET_USERS_KEYS_SUCCESS";
export const GET_USERS_KEYS_FAILURE = "GET_USERS_KEYS_FAILURE";

export const GET_USERS_NOTIFICATION_REQUEST = "GET_USERS_NOTIFICATION_REQUEST";
export const GET_USERS_NOTIFICATION_SUCCESS = "GET_USERS_NOTIFICATION_SUCCESS";
export const GET_USERS_NOTIFICATION_FAILURE = "GET_USERS_NOTIFICATION_FAILURE";
