export const CREATE_PROPERTY_ITEM_REQUEST = " CREATE_PROPERTY_ITEM_REQUEST";
export const CREATE_PROPERTY_ITEM_SUCCESS = " CREATE_PROPERTY_ITEM_SUCCESS";
export const CREATE_PROPERTY_ITEM_FAILURE = " CREATE_PROPERTY_ITEM_FAILURE";

export const GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_REQUEST =
  " GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_REQUEST";
export const GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_SUCCESS =
  " GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_SUCCESS";
export const GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_FAILURE =
  " GET_PROPERTY_ITEMS_BY_REAL_ESTATE_ID_FAILURE";

export const DELETE_PROPERTY_ITEM_REQUEST = " DELETE_PROPERTY_ITEM_REQUEST";
export const DELETE_PROPERTY_ITEM_SUCCESS = " DELETE_PROPERTY_ITEM_SUCCESS";
export const DELETE_PROPERTY_ITEM_FAILURE = " DELETE_PROPERTY_ITEM_FAILURE";

export const SEARCH_PROPERTY_ITEM_REQUEST = " SEARCH_PROPERTY_ITEM_REQUEST";
export const SEARCH_PROPERTY_ITEM_SUCCESS = " SEARCH_PROPERTY_ITEM_SUCCESS";
export const SEARCH_PROPERTY_ITEM_FAILURE = " SEARCH_PROPERTY_ITEM_FAILURE";

export const UPDATE_PROPERTY_ITEMS_AVAILABILITY_REQUEST =
  " UPDATE_PROPERTY_ITEMS_AVAILABILITY_REQUEST";
export const UPDATE_PROPERTY_ITEMS_AVAILABILITY_SUCCESS =
  " UPDATE_PROPERTY_ITEMS_AVAILABILITY_SUCCESS";
export const UPDATE_PROPERTY_ITEMS_AVAILABILITY_FAILURE =
  " UPDATE_PROPERTY_ITEMS_AVAILABILITY_FAILURE";
