export const GET_REAL_ESTATES_KEY_REQUEST = "GET_REAL_ESTATES_KEY_REQUEST";
export const GET_REAL_ESTATES_KEY_SUCCESS = "GET_REAL_ESTATES_KEY_SUCCESS";
export const GET_REAL_ESTATES_KEY_FAILURE = "GET_REAL_ESTATES_KEY_FAILURE";

export const UPDATE_KEY_STATUS_REQUEST = "UPDATE_KEY_STATUS_REQUEST";
export const UPDATE_KEY_STATUS_SUCCESS = "UPDATE_KEY_STATUS_SUCCESS";
export const UPDATE_KEY_STATUS_FAILURE = "UPDATE_KEY_STATUS_FAILURE";
