export const GET_FEATURES = "GET_FEATURES";
export const UPDATE_STOCK = "UPDATE_STOCK";

export const CREATE_FEATURE_REQUEST = "CREATE_FEATURE_REQUEST";
export const CREATE_FEATURE_SUCCESS = "CREATE_FEATURE_SUCCESS";
export const CREATE_FEATURE_FAILURE = "CREATE_FEATURE_FAILURE";

export const CREATE_FEATURE_CATEGORY_REQUEST =
  "CREATE_FEATURE_CATEGORY_REQUEST";
export const CREATE_FEATURE_CATEGORY_SUCCESS =
  "CREATE_FEATURE_CATEGORY_SUCCESS";
export const CREATE_FEATURE_CATEGORY_FAILURE =
  "CREATE_FEATURE_CATEGORY_FAILURE";

export const GET_FEATURE_CATEGORY_REQUEST = "GET_FEATURE_CATEGORY_REQUEST";
export const GET_FEATURE_CATEGORY_SUCCESS = "GET_FEATURE_CATEGORY_SUCCESS";
export const GET_FEATURE_CATEGORY_FAILURE = "GET_FEATURE_CATEGORY_FAILURE";
